source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

target '{{cookiecutter.app_name}}' do

  pod 'R.swift', '5.1.0'
  pod 'SwiftLint', '0.37.0'

  target '{{cookiecutter.app_name}}Tests' do
    pod 'SwiftyMocky', '3.4.0'
    pod 'Quick', '2.1.0'
    pod 'Nimble', '8.0.1'
    pod 'RxBlocking', '4.5.0'
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      config.build_settings['SWIFT_VERSION'] = '5.1'
    end
  end
end
